/**
 * Maps file extensions to their corresponding source block syntax identifiers.
 * Erweitert um alle unterstützten Sprachen des Source Formatters.
 */
export const sourceTypes: Record<string, string> = {
  // A
  "abap": "abap",
  "as": "actionscript",
  "actionscript": "actionscript",
  "ada": "ada",
  "adb": "ada",
  "ads": "ada",
  "conf": "conf", // Config File
  "apache": "apache",
  "cls": "apex",
  "trigger": "apex",
  "apex": "apex",
  "apib": "apiblueprint",
  "applescript": "applescript",
  "scpt": "applescript",
  "s": "armasm",
  "aug": "augeas",
  "awk": "awk",

  // B
  "bat": "batchfile",
  "cmd": "batchfile",
  "bbc": "bbcbasic",
  "bib": "bibtex",
  "bicep": "bicep",
  "biml": "biml",
  "bpf": "bpf",
  "bf": "brainfuck",
  "b": "brainfuck",
  "brs": "brightscript",
  "bsl": "bsl",
  "os": "bsl",

  // C
  "c": "c",
  "h": "c",
  "cs": "csharp",
  "cpp": "cpp",
  "cc": "cpp",
  "cxx": "cpp",
  "hpp": "cpp",
  "hh": "cpp",
  "ceylon": "ceylon",
  "cfc": "cfscript",
  "cfm": "cfscript",
  "clj": "clojure",
  "cljs": "clojure",
  "cljc": "clojure",
  "cmake": "cmake",
  "coffee": "coffeescript",
  "lisp": "common_lisp",
  "lsp": "common_lisp",
  "coq": "coq",
  "cr": "crystal",
  "css": "css",
  "csvs": "csvs",
  "cu": "cuda",
  "cyp": "cypher",
  "cypher": "cypher",
  "pyx": "cython",

  // D - E
  "d": "d",
  "dfy": "dafny",
  "dart": "dart",
  "diff": "diff",
  "patch": "diff",
  "dig": "digdag",
  "dockerfile": "docker",
  "dot": "dot",
  "gv": "dot",
  "ecl": "ecl",
  "eex": "eex",
  "e": "eiffel",
  "ex": "elixir",
  "exs": "elixir",
  "elm": "elm",
  "eml": "email",
  "epp": "epp",
  "erb": "erb",
  "erl": "erlang",
  "hrl": "erlang",

  // F - H
  "factor": "factor",
  "f90": "fortran",
  "f": "fortran",
  "edp": "freefem",
  "fs": "fsharp",
  "fsi": "fsharp",
  "fsx": "fsharp",
  "gd": "gdscript",
  "cmm": "ghc-cmm",
  "hcr": "ghc-core",
  "feature": "gherkin",
  "glsl": "glsl",
  "vert": "glsl",
  "frag": "glsl",
  "go": "go",
  "gradle": "gradle",
  "graphql": "graphql",
  "gql": "graphql",
  "groovy": "groovy",
  "hack": "hack",
  "haml": "haml",
  "hbs": "handlebars",
  "hcl": "hcl",
  "tf": "terraform", // Terraform verwendet typischerweise .tf
  "hs": "haskell",
  "hx": "haxe",
  "hlsl": "hlsl",
  "hocon": "hocon",
  "hql": "hql",
  "html": "html",
  "htm": "html",
  "http": "http",
  "hy": "hylang",

  // I - L
  "pro": "prolog", // .pro wird oft für Prolog genutzt
  "idl": "idlang",
  "idr": "idris",
  "ipf": "igorpro",
  "ini": "ini",
  "io": "io",
  "irb": "irb",
  "thy": "isabelle",
  "isbl": "isbl",
  "ijs": "j",
  "janet": "janet",
  "java": "java",
  "js": "javascript",
  "mjs": "javascript",
  "cjs": "javascript",
  "j2": "jinja",
  "jinja": "jinja",
  "jsl": "jsl",
  "json": "json",
  "json5": "json5",
  "jsonnet": "jsonnet",
  "jsp": "jsp",
  "jsx": "jsx",
  "jl": "julia",
  "kt": "kotlin",
  "kts": "kotlin",
  "lasso": "lasso",
  "lean": "lean",
  "liquid": "liquid",
  "litcoffee": "literate_coffeescript",
  "lhs": "literate_haskell",
  "ls": "livescript",
  "ll": "llvm",
  "lua": "lua",
  "lus": "lustre",
  "lut": "lutin",

  // M - O
  "magik": "magik",
  "mk": "make",
  "mak": "make",
  "md": "markdown",
  "m": "objective_c", // Wird sowohl für Obj-C als auch MATLAB genutzt. Obj-C ist häufiger.
  "matlab": "matlab",
  "meson": "meson",
  "mzn": "minizinc",
  "mojo": "mojo",
  "moon": "moonscript",
  "mos": "mosel",
  "mxml": "mxml",
  "asm": "nasm",
  "nginx": "nginx",
  "ndf": "nial",
  "nim": "nim",
  "nix": "nix",
  "mm": "objective_cpp",
  "ml": "ocaml",
  "mli": "ocaml",
  "ocl": "ocl",
  "p": "openedge",

  // P - R
  "p4": "p4",
  "pas": "pascal",
  "pl": "perl", // Perl ist der Standard für .pl
  "pm": "perl",
  "php": "php",
  "phtml": "php",
  "txt": "plaintext",
  "plist": "plist",
  "pkb": "plsql",
  "pks": "plsql",
  "pony": "pony",
  "ps": "postscript",
  "ps1": "powershell",
  "psm1": "powershell",
  "praat": "praat",
  "prolog": "prolog",
  "proto": "protobuf",
  "pp": "puppet",
  "py": "python",
  "pyw": "python",
  "q": "q",
  "qml": "qml",
  "r": "r",
  "rkt": "racket",
  "re": "reasonml",
  "rei": "reasonml",
  "rego": "rego",
  "res": "rescript",
  "resi": "rescript",
  "rml": "rml",
  "robot": "robot_framework",
  "rb": "ruby",
  "rs": "rust",

  // S - T
  "sas": "sas",
  "sass": "sass",
  "scala": "scala",
  "scm": "scheme",
  "ss": "scheme",
  "scss": "scss",
  "sed": "sed",
  "sh": "shell",
  "sieve": "sieve",
  "ice": "slice",
  "slim": "slim",
  "st": "smalltalk",
  "tpl": "smarty",
  "sml": "sml",
  "rq": "sparql",
  "sqf": "sqf",
  "sql": "sql",
  "ssh": "ssh",
  "stan": "stan",
  "do": "stata",
  "ado": "stata",
  "sc": "supercollider",
  "svelte": "svelte",
  "swift": "swift",
  "service": "systemd",
  "syz": "syzlang",
  "tap": "tap",
  "tcl": "tcl",
  "tex": "tex",
  "toml": "toml",
  "tsx": "tsx",
  "ttcn3": "ttcn3",
  "tlp": "tulip",
  "ttl": "turtle",
  "twig": "twig",
  "ts": "typescript",

  // U - Z
  "vala": "vala",
  "vcl": "vcl",
  "vm": "velocity",
  "v": "verilog",
  "sv": "verilog",
  "veryl": "veryl",
  "vhd": "vhdl",
  "vhdl": "vhdl",
  "vim": "viml",
  "vb": "vb",
  "vue": "vue",
  "wlk": "wollok",
  "xml": "xml",
  "csproj": "xml", // Übernommen aus deinem Original
  "xojo_code": "xojo",
  "xpath": "xpath",
  "xq": "xquery",
  "xquery": "xquery",
  "yaml": "yaml",
  "yml": "yaml",
  "yang": "yang",
  "zig": "zig",

  // Sonstige (AsciiDoc & Diagramme)
  "adoc": "asciidoc",
  "properties": "properties",
  "puml": "plantuml" // Fallback für PlantUML
};