/**
 * Maps file extensions to their corresponding source block syntax identifiers.
 * Erweitert um alle unterstützten Sprachen des Source Formatters.
 */
export const sourceTypes: Record<string, string> = {
  // A
  "abap": "[source,abap]",
  "as": "[source,actionscript]",
  "actionscript": "[source,actionscript]",
  "ada": "[source,ada]",
  "adb": "[source,ada]",
  "ads": "[source,ada]",
  "conf": "[source,conf]", // Config File
  "apache": "[source,apache]",
  "cls": "[source,apex]",
  "trigger": "[source,apex]",
  "apex": "[source,apex]",
  "apib": "[source,apiblueprint]",
  "applescript": "[source,applescript]",
  "scpt": "[source,applescript]",
  "s": "[source,armasm]",
  "aug": "[source,augeas]",
  "awk": "[source,awk]",

  // B
  "bat": "[source,batchfile]",
  "cmd": "[source,batchfile]",
  "bbc": "[source,bbcbasic]",
  "bib": "[source,bibtex]",
  "bicep": "[source,bicep]",
  "biml": "[source,biml]",
  "bpf": "[source,bpf]",
  "bf": "[source,brainfuck]",
  "b": "[source,brainfuck]",
  "brs": "[source,brightscript]",
  "bsl": "[source,bsl]",
  "os": "[source,bsl]",

  // C
  "c": "[source,c]",
  "h": "[source,c]",
  "cs": "[source,csharp]",
  "cpp": "[source,cpp]",
  "cc": "[source,cpp]",
  "cxx": "[source,cpp]",
  "hpp": "[source,cpp]",
  "hh": "[source,cpp]",
  "ceylon": "[source,ceylon]",
  "cfc": "[source,cfscript]",
  "cfm": "[source,cfscript]",
  "clj": "[source,clojure]",
  "cljs": "[source,clojure]",
  "cljc": "[source,clojure]",
  "cmake": "[source,cmake]",
  "coffee": "[source,coffeescript]",
  "lisp": "[source,common_lisp]",
  "lsp": "[source,common_lisp]",
  "coq": "[source,coq]",
  "cr": "[source,crystal]",
  "css": "[source,css]",
  "csvs": "[source,csvs]",
  "cu": "[source,cuda]",
  "cyp": "[source,cypher]",
  "cypher": "[source,cypher]",
  "pyx": "[source,cython]",

  // D - E
  "d": "[source,d]",
  "dfy": "[source,dafny]",
  "dart": "[source,dart]",
  "diff": "[source,diff]",
  "patch": "[source,diff]",
  "dig": "[source,digdag]",
  "dockerfile": "[source,docker]",
  "dot": "[source,dot]",
  "gv": "[source,dot]",
  "ecl": "[source,ecl]",
  "eex": "[source,eex]",
  "e": "[source,eiffel]",
  "ex": "[source,elixir]",
  "exs": "[source,elixir]",
  "elm": "[source,elm]",
  "eml": "[source,email]",
  "epp": "[source,epp]",
  "erb": "[source,erb]",
  "erl": "[source,erlang]",
  "hrl": "[source,erlang]",

  // F - H
  "factor": "[source,factor]",
  "f90": "[source,fortran]",
  "f": "[source,fortran]",
  "edp": "[source,freefem]",
  "fs": "[source,fsharp]",
  "fsi": "[source,fsharp]",
  "fsx": "[source,fsharp]",
  "gd": "[source,gdscript]",
  "cmm": "[source,ghc-cmm]",
  "hcr": "[source,ghc-core]",
  "feature": "[source,gherkin]",
  "glsl": "[source,glsl]",
  "vert": "[source,glsl]",
  "frag": "[source,glsl]",
  "go": "[source,go]",
  "gradle": "[source,gradle]",
  "graphql": "[source,graphql]",
  "gql": "[source,graphql]",
  "groovy": "[source,groovy]",
  "hack": "[source,hack]",
  "haml": "[source,haml]",
  "hbs": "[source,handlebars]",
  "hcl": "[source,hcl]",
  "tf": "[source,terraform]", // Terraform verwendet typischerweise .tf
  "hs": "[source,haskell]",
  "hx": "[source,haxe]",
  "hlsl": "[source,hlsl]",
  "hocon": "[source,hocon]",
  "hql": "[source,hql]",
  "html": "[source,html]",
  "htm": "[source,html]",
  "http": "[source,http]",
  "hy": "[source,hylang]",

  // I - L
  "pro": "[source,prolog]", // .pro wird oft für Prolog genutzt
  "idl": "[source,idlang]",
  "idr": "[source,idris]",
  "ipf": "[source,igorpro]",
  "ini": "[source,ini]",
  "io": "[source,io]",
  "irb": "[source,irb]",
  "thy": "[source,isabelle]",
  "isbl": "[source,isbl]",
  "ijs": "[source,j]",
  "janet": "[source,janet]",
  "java": "[source,java]",
  "js": "[source,javascript]",
  "mjs": "[source,javascript]",
  "cjs": "[source,javascript]",
  "j2": "[source,jinja]",
  "jinja": "[source,jinja]",
  "jsl": "[source,jsl]",
  "json": "[source,json]",
  "json5": "[source,json5]",
  "jsonnet": "[source,jsonnet]",
  "jsp": "[source,jsp]",
  "jsx": "[source,jsx]",
  "jl": "[source,julia]",
  "kt": "[source,kotlin]",
  "kts": "[source,kotlin]",
  "lasso": "[source,lasso]",
  "lean": "[source,lean]",
  "liquid": "[source,liquid]",
  "litcoffee": "[source,literate_coffeescript]",
  "lhs": "[source,literate_haskell]",
  "ls": "[source,livescript]",
  "ll": "[source,llvm]",
  "lua": "[source,lua]",
  "lus": "[source,lustre]",
  "lut": "[source,lutin]",

  // M - O
  "magik": "[source,magik]",
  "mk": "[source,make]",
  "mak": "[source,make]",
  "md": "[source,markdown]",
  "m": "[source,objective_c]", // Wird sowohl für Obj-C als auch MATLAB genutzt. Obj-C ist häufiger.
  "matlab": "[source,matlab]",
  "meson": "[source,meson]",
  "mzn": "[source,minizinc]",
  "mojo": "[source,mojo]",
  "moon": "[source,moonscript]",
  "mos": "[source,mosel]",
  "mxml": "[source,mxml]",
  "asm": "[source,nasm]",
  "nginx": "[source,nginx]",
  "ndf": "[source,nial]",
  "nim": "[source,nim]",
  "nix": "[source,nix]",
  "mm": "[source,objective_cpp]",
  "ml": "[source,ocaml]",
  "mli": "[source,ocaml]",
  "ocl": "[source,ocl]",
  "p": "[source,openedge]",

  // P - R
  "p4": "[source,p4]",
  "pas": "[source,pascal]",
  "pl": "[source,perl]", // Perl ist der Standard für .pl
  "pm": "[source,perl]",
  "php": "[source,php]",
  "phtml": "[source,php]",
  "txt": "[source,plaintext]",
  "plist": "[source,plist]",
  "pkb": "[source,plsql]",
  "pks": "[source,plsql]",
  "pony": "[source,pony]",
  "ps": "[source,postscript]",
  "ps1": "[source,powershell]",
  "psm1": "[source,powershell]",
  "praat": "[source,praat]",
  "prolog": "[source,prolog]",
  "proto": "[source,protobuf]",
  "pp": "[source,puppet]",
  "py": "[source,python]",
  "pyw": "[source,python]",
  "q": "[source,q]",
  "qml": "[source,qml]",
  "r": "[source,r]",
  "rkt": "[source,racket]",
  "re": "[source,reasonml]",
  "rei": "[source,reasonml]",
  "rego": "[source,rego]",
  "res": "[source,rescript]",
  "resi": "[source,rescript]",
  "rml": "[source,rml]",
  "robot": "[source,robot_framework]",
  "rb": "[source,ruby]",
  "rs": "[source,rust]",

  // S - T
  "sas": "[source,sas]",
  "sass": "[source,sass]",
  "scala": "[source,scala]",
  "scm": "[source,scheme]",
  "ss": "[source,scheme]",
  "scss": "[source,scss]",
  "sed": "[source,sed]",
  "sh": "[source,shell]",
  "sieve": "[source,sieve]",
  "ice": "[source,slice]",
  "slim": "[source,slim]",
  "st": "[source,smalltalk]",
  "tpl": "[source,smarty]",
  "sml": "[source,sml]",
  "rq": "[source,sparql]",
  "sqf": "[source,sqf]",
  "sql": "[source,sql]",
  "ssh": "[source,ssh]",
  "stan": "[source,stan]",
  "do": "[source,stata]",
  "ado": "[source,stata]",
  "sc": "[source,supercollider]",
  "svelte": "[source,svelte]",
  "swift": "[source,swift]",
  "service": "[source,systemd]",
  "syz": "[source,syzlang]",
  "tap": "[source,tap]",
  "tcl": "[source,tcl]",
  "tex": "[source,tex]",
  "toml": "[source,toml]",
  "tsx": "[source,tsx]",
  "ttcn3": "[source,ttcn3]",
  "tlp": "[source,tulip]",
  "ttl": "[source,turtle]",
  "twig": "[source,twig]",
  "ts": "[source,typescript]",

  // U - Z
  "vala": "[source,vala]",
  "vcl": "[source,vcl]",
  "vm": "[source,velocity]",
  "v": "[source,verilog]",
  "sv": "[source,verilog]",
  "veryl": "[source,veryl]",
  "vhd": "[source,vhdl]",
  "vhdl": "[source,vhdl]",
  "vim": "[source,viml]",
  "vb": "[source,vb]",
  "vue": "[source,vue]",
  "wlk": "[source,wollok]",
  "xml": "[source,xml]",
  "csproj": "[source,xml]", // Übernommen aus deinem Original
  "xojo_code": "[source,xojo]",
  "xpath": "[source,xpath]",
  "xq": "[source,xquery]",
  "xquery": "[source,xquery]",
  "yaml": "[source,yaml]",
  "yml": "[source,yaml]",
  "yang": "[source,yang]",
  "zig": "[source,zig]",

  // Sonstige (AsciiDoc & Diagramme)
  "adoc": "[source,asciidoc]",
  "properties": "[source,properties]",
  "puml": "[source,plantuml]" // Fallback für PlantUML
};